name: CI
on: [push, pull_request]

jobs:
  main:
    name: Build and publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run CI checks
        run: |
          yarn prettier --list-different '**/*.{js,json,md,ts,yml}'
          yarn compile
          yarn lint
        env:
          CI: true

      - name: Test bin script
        run: |
          node lib/index.js -h
          node lib/index.js create -h
          node lib/index.js start -h
          node lib/index.js upload -h

      - name: Publish to npm
        if:
          matrix.node-version == 12.x && github.event_name == 'release' &&
          github.event.action == 'created'
        run: |
          echo Hello, World!
